### ISSUE TITLE
Do not open a new tab

### ISSUE THREAD

**Issue by JamesDAdams** [rgnet1/tidal-dl#1]
Hello, it would be really good not to open a new tab to display the downloaded music but to display it directly on the page, because personally I use an iframe with tidal-dl and I don't want it to open a new tab.

**Comment by rgnet1** [comment]
Thank you for the suggestion! I will look into it

**Comment by JamesDAdams** [comment]
> Thank you for the suggestion! I will look into it

Thanks

**Comment by rgnet1** [comment]
Thank you for the suggestion. Please try the latest release. I implemented your suggestion in commit: 7a1de547f712067f6ffc3cb0d583e7f68af5de9b

**Comment by JamesDAdams** [comment]
![image](https://user-images.githubusercontent.com/20860324/134220237-3184e317-7d02-44e7-be65-c744d29b05ed.png)


> ----------------Starting new download. New album ----------------
EOF error
b'\r\n /$$$$$$$$ /$$ /$$ /$$ /$$ /$$\r\n|__ $$__/|__/ | $$ | $$ | $$| $$\r\n | $$ /$$ /$$$$$$$ /$$$$$$ | $$ /$$$$$$$| $$\r\n | $$ | $$ /$$__ $$ |____ $$| $$ /$$$$$$ /$$__ $$| $$\r\n | $$ | $$| $$ | $$ /$$$$$$$| $$|______/| $$ | $$| $$\r\n | $$ | $$| $$ | $$ /$$__ $$| $$ | $$ | $$| $$\r\n | $$ | $$| $$$$$$$| $$$$$$$| $$ | $$$$$$$| $$\r\n |__/ |__/ \\_______/ \\_______/|__/ \\_______/|__/\r\n \r\n https://github.com/yaronzz/Tidal-Media-Downloader \r\n\r\n v2021.3.24.1\x1b[0m\r\n\x1b[0m+-----------------------+------------------------------------------------------------+\r\n| \x1b[32mSETTINGS\x1b[0m | \x1b[32mVALUE\x1b[0m |\r\n+-----------------------+------------------------------------------------------------+\r\n| Settings path | /production/www/cgi-bin |\r\n| Download path | ./download/ |\r\n| Convert mp4 to m4a | False |\r\n| Audio quality | AudioQuality.Normal |\r\n| Video quality | VideoQuality.P360 |\r\n| Check exist | True |\r\n| Show progress | True |\r\n| Include single&ep | True |\r\n| Save covers | True |\r\n| Language | English |\r\n| Use playlist folder | True |\r\n| Multi thread download | True |\r\n| Album folder format | {ArtistName}/{Flag} {AlbumTitle} [{AlbumID}] [{AlbumYear}] |\r\n| Track file format | {TrackNumber} - {ArtistName} - {TrackTitle}{ExplicitFlag} |\r\n+-----------------------+------------------------------------------------------------+\x1b[0m\r\n\x1b[0mTraceback (most recent call last):\r\n\x1b[0m File "/usr/local/bin/tidal-dl", line 8, in \r\n\x1b[0m \x1b[0msys.exit(main())\x1b[0m\r\n\x1b[0m File "/usr/local/lib/python3.8/dist-packages/tidal_dl/__init__.py", line 236, in main\r\n\x1b[0m \x1b[0mcheckLogin()\x1b[0m\r\n\x1b[0m File "/usr/local/lib/python3.8/dist-packages/tidal_dl/__init__.py", line 128, in checkLogin\r\n\x1b[0m \x1b[0mif not isNull(TOKEN.accessToken):\x1b[0m\r\n\x1b[0mAttributeError\x1b[0m: \x1b[0m\'NoneType\' object has no attribute \'accessToken\'\x1b[0m\r\n\x1b[0m\x1b[0m'
-----------COPLETED ALL SONGS------------------
Total number of songs: 0

**Comment by rgnet1** [comment]
This is most likely an issue with the version of tidal-dl. I went ahead and updated the tidal-dl. With the updated container here's what I'm getting:
![result](https://user-images.githubusercontent.com/12654681/135218834-348aea4e-92f7-4f43-ac75-41a860afeac5.jpg)

Please try again, and let me know if it is still broken. I'm happy to fix it.

**Comment by JamesDAdams** [comment]
yes it's work thanks :)
