### ISSUE TITLE
Can't download over WebUI

### ISSUE THREAD

**Issue by MauliQT** [rgnet1/tidal-dl#11]
I can log in over the web ui but when i start a download i get no message, the right window just stays blank. Any way to fix this?

**Comment by rgnet1** [comment]
Let me see if i can get a better knolege of your setup, what's your docker-compose or docker run command look like? 

Are you using the lates build?

 Have you tried starting the container from scratch with no provided tidal-dl settings or token?

**Comment by MauliQT** [comment]
version: "3"

services:
  tidal-dl:
    container_name: tidal-local
    image: rgnet1/tidal-dl:latest
    ports:
      - "8885:80"
    volumes:
      - '/test/Music:/production/www/cgi-bin/download/'
      - '/test/config:/production/www/cgi-bin/configuration/'

**Comment by MauliQT** [comment]
In the setting i changed the download folder setting to /production/www/cgi-bin/download/ but nothing else

**Comment by rgnet1** [comment]
1. Try deleting files inside of /test/config/ on your system
2.  Shut down the container, and re-pull it from dockerhub. (i made one fix for the symptoms of your issue a couple of days ago so i want to eliminate that is the problem)
4. Restart the container and try again - you'll need to re-login

**Comment by MauliQT** [comment]
I pulled and set up the container today, also the config folder is completely empty

**Comment by rgnet1** [comment]
Gotcha. thanks for the context. It looks like the configuration for tidal-dl is not being created. What system is your host on? If it's Ubuntu or Debian based distribution, I recommend trying privilege mode (see readme for it). In the mean time I'll try replicating the issue and working on a fix

**Comment by MauliQT** [comment]
yeah im using ubuntu

**Comment by MauliQT** [comment]
![settin](https://user-images.githubusercontent.com/87561264/200668045-4a2b413a-8550-46eb-aebb-b8d25bf317fe.PNG)

**Comment by MauliQT** [comment]
Tried with privilege mode didn't work /: 
Still have the same problem

**Comment by rgnet1** [comment]
You should not be accessing tidal-dl from the terminal with my container. When you log into the container you are using the root user, however, the "web version" for security is only using by the www-data user. So any tidal-dl configuration you apply as the root user will not work for web UI because its using the www-data user.

Hopefully that explains why logging into the container won't work. I'll see what I can do to replicate your issue. Let me get back to you. Thanks for the info and trying out my project.

**Comment by rgnet1** [comment]
Can you show me what your settings.json file looks like in your host's /test/config/ folder?

**Comment by MauliQT** [comment]
![Capture](https://user-images.githubusercontent.com/87561264/201473957-a7a1c488-3ffb-40ea-8505-c303208741a5.PNG)
Like I said its completely empty

**Comment by MauliQT** [comment]
I know the error now, its so stupid, the perms weren't set for the config folder

**Comment by christorepl** [comment]
weird. i had this same issue and it turns out it was a permissions issue on the config folder, and download folder as well. not sure how permissions got borked.
