### ISSUE TITLE
tidal login 

### ISSUE THREAD

**Issue by matthes-me** [rgnet1/tidal-dl#3]
I've done the login and I'm still getting this message

----- Starting new download. New album ----------------
Waiting for you to register ....
You need to use docker cli and run command: docker exec -it tidal-dl ./tidal-login.sh
unRAID users: simply open the console and run: ./tidal-login.sh

**Comment by rgnet1** [comment]
There are some login issues due to the version of tidal-dl that is running. I am working on a fix

**Comment by rgnet1** [comment]
@matthes-me  Can you try the development version : `rgnet1/tidal-dl:development` and let me know if it works for you

**Comment by rgnet1** [comment]
Hi I believe a fix has been applied. Please update the container.

If that doesn't work then you are using an outdated settings or token file so try following the instructions [here](https://github.com/rgnet1/tidal-dl/issues/4#issuecomment-1024971077)
