### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by JamesDAdams** [rgnet1/tidal-dl#4]
Does not work anymore

![image](https://user-images.githubusercontent.com/20860324/150594754-fd463464-d210-45aa-bbe1-ddf96ff7b020.png)

**Comment by rgnet1** [comment]
The new Tidal Plans changed the way Tidal-Dl works. Not to worry, I am working on a fix

**Comment by rgnet1** [comment]
I went and uploaded the fix the development branch. Can you please try the development build and let me know if it works?

`rgnet1/tidal-dl:development`

**Comment by Me0wzz** [comment]
I tried development branch but, It didn't work.
Using Ubuntu 20.04 LTS (aarch64)

I did 
```
docker run -d \
  --name=tidal-dl \
  -v ~/docker/tidal-dl/download/:/production/www/cgi-bin/download/Album/ \
  -v ~/.tidal-dl.json:/production/www/cgi-bin/.tidal-dl.json \
  -v ~/.tidal-dl.token.json:/production/www/cgi-bin/.tidal-dl.token.json \
  rgnet1/tidal-dl:development
```
(I use Nginx Proxy Manager so, I did not set any port)

Next, I did
```
docker exec -it tidal-dl ./tidal-login.sh
```

It says "Device authorization failed". So, I typed "5" and changed API token to "3 (TV)" and exit with "0".

I accessed Web UI and pasted tidal song link.
Then, it shows

```
----------------Starting new download. New track ----------------
Finished download from current track

-----------COPLETED ALL SONGS------------------
Total number of songs: 0
```

I checked /production/www/cgi-bin/download/Album/ in container but, music didn't download.
Is there any problem setting up container?
I also compiled image(development branch) but I got same result.

**Comment by JamesDAdams** [comment]
> I went and uploaded the fix the development branch. Can you please try the development build and let me know if it works?
> 
> `rgnet1/tidal-dl:development`
> 
> If it works, I'll push the changes to master

I test and it's work with the cli, but doesn't work on the web :(

**Comment by JamesDAdams** [comment]
It would be nice a system to connect to tidal from the website, without having to connect in cli

**Comment by JamesDAdams** [comment]
the config folder is not detected /production/www/cgi-bin/.tidal-dl.json

**Comment by rgnet1** [comment]
Make sure you update your the .tidal-dl.json file. New additions to tidal-dl added new settings in the json file. You can copy and paste all of them in the README (on developmnet). 

Secondly you may need a new json token with the updated version of tidal-dl

**Comment by rgnet1** [comment]
@Me0wzz  if updating your local ~/.tidal-dl.json settings file does not work, please make sure you run the container with privileged mode. Ubuntu and other debian OSes may need it:
`privileged: true`

**Comment by JamesDAdams** [comment]
> Make sure you update your local `~/.tidal-dl.json` settings file. New additions to tidal-dl added new settings in the json file. You can copy and paste all of them in the README (on developmnet).
> 
> Secondly you may need a new json token with the updated version of tidal-dl. But it looks like you're good since you re-ran the login script :)
> 
> Thank you for the detailed explanation of your set up. It helps with debugging your issue. Let me know how updating your settings file works

I edit my tidal-dl.json with the new config and it's doesn't work, i have this : 

![image](https://user-images.githubusercontent.com/20860324/150694789-347b26bd-ab22-445c-a89d-cd24350d3eee.png)

**Comment by rgnet1** [comment]
@JamesDAdams Whoops. I messed up in the README. Please change the download path is set as follows:
`"downloadPath": "/production/www/cgi-bin/download/",`

**Comment by JamesDAdams** [comment]
> @JamesDAdams Whoops. I messed up in the README. Please change the download path is set as follows: `"downloadPath": "/production/www/cgi-bin/download/",`

This is what I have in my file, but it looks like it doesn't take into account my configuration file

**Comment by JamesDAdams** [comment]
no matter what I put in my config file it does not change anything it has the config that I sent you in picture

**Comment by rgnet1** [comment]
Yes that makes sense. This is because the web-gui runs tidal-dl with the user:  `www-data`. This is the "web user".

However when we run into the container we are always using the user: `root`. Can you log into the container and show me the output of the following commands:

```
cd /production/www/cgi-bin
ls -alh
```
Here you should see the `.tidal-dl.json` and `.tidal-dl.token.json` files belong to `root`, but other files belong to `www-data`

Next, can you show me the output of the following:
`cat .tidal-dl.json`
You should see your json file changes now

**Comment by JamesDAdams** [comment]
![image](https://user-images.githubusercontent.com/20860324/150695847-75307baf-81f3-44f1-bc74-ab89e2aca8e8.png)

![image](https://user-images.githubusercontent.com/20860324/150695866-a5e4526e-33db-4b7e-95e6-e92438705daf.png)

**Comment by rgnet1** [comment]
Okay. It l ooks like you are missing some of the new settings that are required by the version of tidal-dl. Here's what it is supposed to look like. Some of these settings include` "read":null,` and ` "save":null,`

![image](https://user-images.githubusercontent.com/12654681/150697923-73ede655-d2cd-4fc2-b5a7-609f4501a980.png)

**Comment by rgnet1** [comment]
I recommend updating the latest version of tidal-dl locally on your system. Then use that tidal-dl.json file as your file that you volume map into the container

**Comment by Me0wzz** [comment]
@rgnet1 I edited download path (`./download/`) to `/production/www/cgi-bin/download/ and gave privileged option. Now, It downloads music properly now. Thanks for your hard work.

**Comment by Me0wzz** [comment]
I think [settings.py](https://github.com/rgnet1/tidal-dl/blob/development/copy-files/settings.py) is overriding the "downloadPath" to `./download/`.

**Comment by rgnet1** [comment]
@Me0wzz I believe the issue was with privileged option not being enabled. However, I went ahead and changed Settings.py to include the correct download location: `/production/www/cgi-bin/download/ ` It's in the latest development build

**Comment by rgnet1** [comment]
@JamesDAdams Were you able to get yours working?

**Comment by JamesDAdams** [comment]
Hi, sorry, I didn't have time to test before.

No, it's doesn't work, i link the .tidal-dl.token.json in /root/.tidal-dl.token.json and it's work, but impossible to link the config file

**Comment by rgnet1** [comment]
No problem. Just want to help you get it working again - a few items:
1. Can you install the latest tidal-dl on your system (not my container - the regular cli tidal-dl) , and login to generate a token file?
2. use that token file, and volume map it to the correct location in the container - you can find volume mapping in the container
3. With the new tidal-dl installed also use that configuration file
4. Use the mappings found in the readme to map both files. Do  not map to /root/
5. Can you post what your docker run command or compose-file is?

**Comment by JamesDAdams** [comment]
No, because the problem does not come from the token, because I manage to recover one, the problem comes from the mapping of the files in the docker container.

my docker run command : 

docker run -d 
--name=tidal-dl \
-p 8885:80 \ 
-v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/download/:/production/www/cgi-bin/download/Album/ \
-v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/.tidal-dl.json:/production/www/cgi-bin/.tidal-dl.json \
-v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/tidal-dl.token.json:/production/www/cgi-bin/.tidal-dl.token.json \ rgnet1/tidal-dl

**Comment by Me0wzz** [comment]
@JamesDAdams  Maybe I think dot(.)  is missing for .tidal-dl.token.json file on this line 

`-v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/tidal-dl.token.json:/production/www/cgi-bin/.tidal-dl.token.json \ `

This should be changed to

`-v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/.tidal-dl.token.json:/production/www/cgi-bin/.tidal-dl.token.json \ `

**Comment by JamesDAdams** [comment]
> @JamesDAdams Maybe I think dot(.) is missing for .tidal-dl.token.json file on this line
> 
> `-v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/tidal-dl.token.json:/production/www/cgi-bin/.tidal-dl.token.json \ `
> 
> This should be changed to
> 
> `-v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/.tidal-dl.token.json:/production/www/cgi-bin/.tidal-dl.token.json \ `

no there is and the problem is for the config not the token

**Comment by rgnet1** [comment]
@JamesDAdams  Try this command:

docker run -d
--name=tidal-dl
-p 8885:80 \
-v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/download/:/production/www/cgi-bin/download/Album/
-v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/.tidal-dl.json:/production/www/cgi-bin/.tidal-dl.json
-v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/tidal-dl.token.json:/production/www/cgi-bin/.tidal-dl.token.json \ rgnet1/tidal-dl:development

**Comment by JamesDAdams** [comment]
> @JamesDAdams Try this command:
> 
> docker run -d --name=tidal-dl -p 8885:80 -v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/download/:/production/www/cgi-bin/download/Album/ -v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/.tidal-dl.json:/production/www/cgi-bin/.tidal-dl.json -v /home/jamesadams/Téléchargements/Hanana/test/tidal-dl/tidal-dl.token.json:/production/www/cgi-bin/.tidal-dl.token.json \ rgnet1/tidal-dl:development

Doesn't work

![image](https://user-images.githubusercontent.com/20860324/151660355-f26441db-948b-47c6-bbcb-d8febf67b009.png)

**Comment by JamesDAdams** [comment]
i map the config and token in root folder and it's work with the cli but not on the web

**Comment by JamesDAdams** [comment]
![image](https://user-images.githubusercontent.com/20860324/151661255-9daf32db-e3ef-4787-94d8-d842e63c0ac3.png)

**Comment by rgnet1** [comment]
After running my command you cannot use the cli to verify it is working because the cli uses the root user.

Mapping to root will not work. As I said earlier, when you log into the container manually you are using the root user - you see the hashtag as the prompt. However the GUI is using a we "web user" So you need to map the 2 files to the directory that the web user has control over:  `/production/www/cgi-bin` and no where else.

You can see the web user called "www-data" has control over this folder (first line of the ls -alh command in the screenshot below)
![image](https://user-images.githubusercontent.com/12654681/151673934-61bbd26b-0541-4555-938c-3281c0c275a1.png)

Your` .tidal-dl.json` file and your `.tidal-dl.token.json` file should be mounted to this folder ONLY. This is because the web user: www-data only has access to that folder. This also means running tidal in the CLI will not work

**Comment by rgnet1** [comment]
Can you try not mounting any token or settings file? and manually log-into docker with the login script:

1. Start the container
docker run -d \
  --name=tidal-dl \
  -p 8885:80 \
  -v ~/download/:/production/www/cgi-bin/download/Album/ 
  rgnet1/tidal-dl:development

2. Run the login script -  Log into the container CLI and run the comand:
./tidal-login.sh

**Comment by JamesDAdams** [comment]
> Can you try not mounting any token or settings file? and manually log-into docker with the login script:
> 
> 1. Start the container
>    docker run -d 
>      --name=tidal-dl 
>      -p 8885:80 
>      -v ~/download/:/production/www/cgi-bin/download/Album/
>    rgnet1/tidal-dl:development
> 2. Run the login script -  Log into the container CLI and run the command:
>    ./tidal-login.sh

![image](https://user-images.githubusercontent.com/20860324/151845304-ecd66860-ad76-4e82-9126-866c448aa858.png)

**Comment by JamesDAdams** [comment]
ok it's work now

**Comment by rgnet1** [comment]
great to hear. I'll go ahead and close the issue. Looks like it came down to using an outdated settings file or token file
